name: Rebuild Caddy Git

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/rebuild.yml'
      - 'Dockerfile'
      - 'Caddyfile'
  schedule:
    - cron: "20 */4 * * *"
  workflow_dispatch:  # Allow manual triggering

jobs:
  rebuild-caddy:
    name: Rebuild and Push Caddy Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/caddy
          tags: |
            type=raw,value=latest
            type=sha,prefix={{date 'YYYYMMDDHHmmss'}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64